# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import comm.service_pb2 as service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LearnerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getAction = channel.unary_unary(
                '/seedling_rl.Learner/getAction',
                request_serializer=service__pb2.Request.SerializeToString,
                response_deserializer=service__pb2.Response.FromString,
                _registered_method=True)
        self.getActionStream = channel.stream_stream(
                '/seedling_rl.Learner/getActionStream',
                request_serializer=service__pb2.Request.SerializeToString,
                response_deserializer=service__pb2.Response.FromString,
                _registered_method=True)


class LearnerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getActionStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LearnerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getAction': grpc.unary_unary_rpc_method_handler(
                    servicer.getAction,
                    request_deserializer=service__pb2.Request.FromString,
                    response_serializer=service__pb2.Response.SerializeToString,
            ),
            'getActionStream': grpc.stream_stream_rpc_method_handler(
                    servicer.getActionStream,
                    request_deserializer=service__pb2.Request.FromString,
                    response_serializer=service__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'seedling_rl.Learner', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('seedling_rl.Learner', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Learner(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/seedling_rl.Learner/getAction',
            service__pb2.Request.SerializeToString,
            service__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getActionStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/seedling_rl.Learner/getActionStream',
            service__pb2.Request.SerializeToString,
            service__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
