# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x0bseedling_rl\"\x1e\n\x07Request\x12\x13\n\x0bobservation\x18\x01 \x01(\x0c\"\x1a\n\x08Response\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\x0c\x32\x8b\x01\n\x07Learner\x12:\n\tgetAction\x12\x14.seedling_rl.Request\x1a\x15.seedling_rl.Response\"\x00\x12\x44\n\x0fgetActionStream\x12\x14.seedling_rl.Request\x1a\x15.seedling_rl.Response\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=30
  _globals['_REQUEST']._serialized_end=60
  _globals['_RESPONSE']._serialized_start=62
  _globals['_RESPONSE']._serialized_end=88
  _globals['_LEARNER']._serialized_start=91
  _globals['_LEARNER']._serialized_end=230
# @@protoc_insertion_point(module_scope)
